#!/bin/sh
#
# Contain Environment variables for installs
#

HOME_DIR="/home/vagrant"

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

FITS_VERSION=0.10.0
