#!/bin/sh

case "$1" in
  start)
    echo "Starting Fedora and Solr"
    su - vagrant -c "/bin/sh -c 'cd /home/vagrant/curation-concerns-demo; nohup fcrepo_wrapper -p 8984 -i tmp > log/fedora.log 2>&1 &'"
    su - vagrant -c "/bin/sh -c 'cd /home/vagrant/curation-concerns-demo; nohup solr_wrapper --version 5.4.1 -d solr/config/ -p 8983 -n hydra-development --download_path tmp/solr.war -i tmp/solr > log/solr.log 2>&1 &'"
    ;;
  stop)
    ;;
esac

printf 'waiting for solr and fedora'
until $(curl --output /dev/null --silent --head --fail http://localhost:8983/solr); do
  printf '.'
  sleep 1
done
until $(curl --output /dev/null --silent --head --fail http://localhost:8984/rest); do
  printf '.'
  sleep 1
done
echo " done"

exit 0
